# This is a basic workflow to help you get started with Actions

name: yarnbuild

# Controls when the action will run. 
on:
 push:
  tags: 
    - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: init node env
        uses: actions/setup-node@v2.1.5
      - name: Yarn install cache
        uses: c-hive/gha-yarn-cache@v1
      - name: install yarn dep
        run: yarn install
      - name: build static files
        run: yarn build
      - name: package build
        run: tar -zcvf ./build.tar.gz ./build 
      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
